# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ipopt_model')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ipopt_model')
    _ipopt_model = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ipopt_model', [dirname(__file__)])
        except ImportError:
            import _ipopt_model
            return _ipopt_model
        try:
            _mod = imp.load_module('_ipopt_model', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ipopt_model = swig_import_helper()
    del swig_import_helper
else:
    import _ipopt_model
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class IpoptModel(_object):
    """Proxy of C++ IpoptModel class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IpoptModel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IpoptModel, name)
    __repr__ = _swig_repr

    def add_constraint(self, arg2):
        """
        add_constraint(IpoptModel self, std::shared_ptr< ConstraintBase > arg2)

        Parameters
        ----------
        arg2: std::shared_ptr< ConstraintBase >

        """
        return _ipopt_model.IpoptModel_add_constraint(self, arg2)


    def remove_constraint(self, arg2):
        """
        remove_constraint(IpoptModel self, std::shared_ptr< ConstraintBase > arg2)

        Parameters
        ----------
        arg2: std::shared_ptr< ConstraintBase >

        """
        return _ipopt_model.IpoptModel_remove_constraint(self, arg2)


    def add_var(self, arg2):
        """
        add_var(IpoptModel self, std::shared_ptr< Var > arg2)

        Parameters
        ----------
        arg2: std::shared_ptr< Var >

        """
        return _ipopt_model.IpoptModel_add_var(self, arg2)


    def remove_var(self, arg2):
        """
        remove_var(IpoptModel self, std::shared_ptr< Var > arg2)

        Parameters
        ----------
        arg2: std::shared_ptr< Var >

        """
        return _ipopt_model.IpoptModel_remove_var(self, arg2)


    def set_objective(self, arg2):
        """
        set_objective(IpoptModel self, std::shared_ptr< Objective > arg2)

        Parameters
        ----------
        arg2: std::shared_ptr< Objective >

        """
        return _ipopt_model.IpoptModel_set_objective(self, arg2)


    def solve(self):
        """
        solve(IpoptModel self)

        Parameters
        ----------
        self: IpoptModel *

        """
        return _ipopt_model.IpoptModel_solve(self)

    __swig_setmethods__["obj"] = _ipopt_model.IpoptModel_obj_set
    __swig_getmethods__["obj"] = _ipopt_model.IpoptModel_obj_get
    if _newclass:
        obj = _swig_property(_ipopt_model.IpoptModel_obj_get, _ipopt_model.IpoptModel_obj_set)
    __swig_setmethods__["vars"] = _ipopt_model.IpoptModel_vars_set
    __swig_getmethods__["vars"] = _ipopt_model.IpoptModel_vars_get
    if _newclass:
        vars = _swig_property(_ipopt_model.IpoptModel_vars_get, _ipopt_model.IpoptModel_vars_set)
    __swig_setmethods__["cons"] = _ipopt_model.IpoptModel_cons_set
    __swig_getmethods__["cons"] = _ipopt_model.IpoptModel_cons_get
    if _newclass:
        cons = _swig_property(_ipopt_model.IpoptModel_cons_get, _ipopt_model.IpoptModel_cons_set)
    __swig_setmethods__["solver_status"] = _ipopt_model.IpoptModel_solver_status_set
    __swig_getmethods__["solver_status"] = _ipopt_model.IpoptModel_solver_status_get
    if _newclass:
        solver_status = _swig_property(_ipopt_model.IpoptModel_solver_status_get, _ipopt_model.IpoptModel_solver_status_set)
    __swig_setmethods__["hessian_map"] = _ipopt_model.IpoptModel_hessian_map_set
    __swig_getmethods__["hessian_map"] = _ipopt_model.IpoptModel_hessian_map_get
    if _newclass:
        hessian_map = _swig_property(_ipopt_model.IpoptModel_hessian_map_get, _ipopt_model.IpoptModel_hessian_map_set)

    def __init__(self):
        """__init__(IpoptModel self) -> IpoptModel"""
        this = _ipopt_model.new_IpoptModel()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ipopt_model.delete_IpoptModel
    __del__ = lambda self: None
IpoptModel_swigregister = _ipopt_model.IpoptModel_swigregister
IpoptModel_swigregister(IpoptModel)

# This file is compatible with both classic and new-style classes.


