name: wntr
dependencies:
    - python=3.11
    - numpy
    - scipy
    - networkx
    - pandas
    - matplotlib
    - sphinx
    - numpydoc
    - docutils<0.17
    - sphinx_design
    - pydata_sphinx_theme
    - sphinxcontrib-bibtex
