# This is a basic workflow to help you get started with Actions

name: docs build experiment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, docstrings ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pandoc
        run: sudo apt-get update -y && sudo apt-get install -y pandoc
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.8' 
      - name: Setup Python 3.8
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install --upgrade coverage pytest
      - name: Install package
        run: |
          python -m pip install -e .
      - name: Build documentation
        run: sphinx-build -b html docs/ docs/_build/html
      - uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html
