# This is a basic workflow to help you get started with Actions

name: build docs artifact

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pandoc
        run: sudo apt-get update -y && sudo apt-get install -y pandoc
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.8' 
      - name: Setup Python 3.8
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install --upgrade coverage pytest
      - name: Install package
        run: |
          python -m pip install -e .
      - name: Build documentation
        run: sphinx-build -b html docs/ docs/_build/html
      - uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html
