# This is a basic workflow to help you get started with Actions

name: Build docs and deploy to pages

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pandoc
        run: sudo apt-get update -y && sudo apt-get install -y pandoc
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.8' 
      - name: Setup Python 3.8
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install --upgrade coverage pytest
      - name: Install package
        run: |
          python setup.py develop --build
      - name: Build documentation
        run: sphinx-build -b html documentation/ documentation/_build/html
      - uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: documentation/_build/html

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: html-docs
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
