# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: quick-check

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.9', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade coverage pytest
    - name: Install package for development
      run: |
        python -m pip install -e .
    - name: Run tests and coverage (unittests plus doctests)
      run: |
        coverage run --source=wntr --omit="*/tests/*","*/sim/network_isolation/network_isolation.py","*/sim/aml/evaluator.py" -m pytest -m "not time_consuming" --doctest-modules --doctest-glob="*.rst" wntr        
        coverage report --fail-under=70        
    # coverage run --source=wntr --omit="*/tests/*" --append -m pytest --doctest-glob="*.rst" documentation 

